spring:
  application:
    name: discovery-service

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}"

  cloud:
    config:
      label: develop
      fail-fast: false
      retry:
        max-attempts: 10
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000
